### ISSUE TITLE
Wrong config.def.h

### ISSUE THREAD

**Issue by ghost** [dracula/dmenu#1]
The config.def.h file in the repository contains the default config for dmenu instead of the correct colors for the Dracula theme.

**Comment by Ellipogus** [comment]
Sorry for the long wait, fixed now

**Comment by Jayanth-Parthsarathy** [comment]
Hey @Ellipogus . I think the config file is still not fixed. I would love to work on this issue and fix the config file.
